#属性名不支持驼峰，可以用'-'代替
server:
    address: 127.0.0.1
    port: 8088
    servlet:
        context-path: /yangqu

debug: true

spring:
    datasource:
        zonedata:
            name: zoneData
            #务必要用jdbcurl，HikariDataSource连接池没有url属性
            jdbcurl: jdbc:mysql://127.0.0.1:3306/baggio_zone_data?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
            username: root
            password:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
        zonelog:
            name: zoneLog
            jdbcurl: jdbc:mysql://127.0.0.1:3306/baggio_zone_log?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
            username: root
            password:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver
        worlddata:
            name: worldData
            jdbcurl: jdbc:mysql://127.0.0.1:3306/baggio_world_data?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
            username: root
            password:
            type: com.zaxxer.hikari.HikariDataSource
            driver-class-name: com.mysql.jdbc.Driver

#        druid:
#          max-wait: 60000
#          max-active: 20
#          initial-size: 1
#          min-idle: 1
#          time-between-eviction-runs-millis: 60000
#          validation-query: select 'x'
#          test-while-idle: true
#          test-on-borrow: false
#          test-on-return: false
#          pool-prepared-statements: true
#          max-open-prepared-statements: 20


    freemarker:
        cache: false
    mvc:
      #设置静态文件路径，js，css等
      static-path-pattern: /static/**

mybatis:
    mapper-locations: classpath:mapping/*/*.xml


